language: generic 
sudo: required
services: 
    - docker

before_install:
    - docker build -t rishikesj0209/docker-react -f  Dockerfile.dev .

script:
    - docker run -e CI=true rishikesj0209/docker-react npm run test -- --coverage