version : '3'
services:
    web:
        build: 
            context: . # where to look 
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        volumes:
            - /app/node_modules
            - .:/app    #map folders outside the container to inside the app in a container
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
    test:
        build: 
            context: . # where to look 
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app    #map folders outside the container to inside the app in a container
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
        command: ["npm","run","test"]  #overwrite the CMD 
    
    